sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_bb7a40693878_key -iv $encrypted_bb7a40693878_iv -in travis-deployer.json.enc -out travis-deployer.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file travis-deployer.json
  